<a href="https://colab.research.google.com/github/aytekin827/TIL/blob/main/pytorch%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

torch.sum() 이해하기

In [ ]:
import torch
import torch.nn as nn

# 2차원 텐서 계산

In [ ]:
a=  torch.arange(4*4).view(4,4)
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [ ]:
torch.sum(a) # 모두 다 더함

tensor(120)

In [ ]:
torch.sum(a,dim=0) # 열을 기준으로 더함

tensor([24, 28, 32, 36])

In [ ]:
torch.sum(a, dim=1) # 행을 기준으로 더함

tensor([ 6, 22, 38, 54])

# 3차원 이상 텐서 계산

In [ ]:
x = torch.arange(2*3*4).view(2,3,4)
print(x.shape)
print(x)

torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [ ]:
torch.sum(x) # 모두 다 더함

tensor(276)

In [ ]:
print(torch.sum(x, dim=0).shape)
torch.sum(x, dim=0)
# 0번째 인덱스에 있는 차원이 더해져 없어진다.

torch.Size([3, 4])


tensor([[12, 14, 16, 18],
        [20, 22, 24, 26],
        [28, 30, 32, 34]])

In [ ]:
print(torch.sum(x, dim=1).shape)
torch.sum(x, dim=1)
# 1번째 인덱스에 있는 차원이 더해져 없어진다.

torch.Size([2, 4])


tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

In [ ]:
print(torch.sum(x, dim=2).shape)
torch.sum(x, dim=2)
# 2번째 인덱스에 있는 차원이 더해져 없어진다.

torch.Size([2, 3])


tensor([[ 6, 22, 38],
        [54, 70, 86]])

# 4차원 텐서 계산


In [ ]:
q = torch.arange(2*3*4*5).view(2,3,4,5)
print(q.shape)
print(q)

torch.Size([2, 3, 4, 5])
tensor([[[[  0,   1,   2,   3,   4],
          [  5,   6,   7,   8,   9],
          [ 10,  11,  12,  13,  14],
          [ 15,  16,  17,  18,  19]],

         [[ 20,  21,  22,  23,  24],
          [ 25,  26,  27,  28,  29],
          [ 30,  31,  32,  33,  34],
          [ 35,  36,  37,  38,  39]],

         [[ 40,  41,  42,  43,  44],
          [ 45,  46,  47,  48,  49],
          [ 50,  51,  52,  53,  54],
          [ 55,  56,  57,  58,  59]]],


        [[[ 60,  61,  62,  63,  64],
          [ 65,  66,  67,  68,  69],
          [ 70,  71,  72,  73,  74],
          [ 75,  76,  77,  78,  79]],

         [[ 80,  81,  82,  83,  84],
          [ 85,  86,  87,  88,  89],
          [ 90,  91,  92,  93,  94],
          [ 95,  96,  97,  98,  99]],

         [[100, 101, 102, 103, 104],
          [105, 106, 107, 108, 109],
          [110, 111, 112, 113, 114],
          [115, 116, 117, 118, 119]]]])


In [ ]:
torch.sum(q) # 모두 다 더함

tensor(7140)

In [ ]:
print(torch.sum(q, dim=0).shape)
torch.sum(q, dim=0)
# 0번째 인덱스에 있는 차원이 더해져 없어진다.

torch.Size([3, 4, 5])


tensor([[[ 60,  62,  64,  66,  68],
         [ 70,  72,  74,  76,  78],
         [ 80,  82,  84,  86,  88],
         [ 90,  92,  94,  96,  98]],

        [[100, 102, 104, 106, 108],
         [110, 112, 114, 116, 118],
         [120, 122, 124, 126, 128],
         [130, 132, 134, 136, 138]],

        [[140, 142, 144, 146, 148],
         [150, 152, 154, 156, 158],
         [160, 162, 164, 166, 168],
         [170, 172, 174, 176, 178]]])

In [ ]:
print(torch.sum(q, dim=1).shape)
torch.sum(q, dim=1)
# 1번째 인덱스에 있는 차원이 더해져 없어진다.

torch.Size([2, 4, 5])


tensor([[[ 60,  63,  66,  69,  72],
         [ 75,  78,  81,  84,  87],
         [ 90,  93,  96,  99, 102],
         [105, 108, 111, 114, 117]],

        [[240, 243, 246, 249, 252],
         [255, 258, 261, 264, 267],
         [270, 273, 276, 279, 282],
         [285, 288, 291, 294, 297]]])

In [ ]:
print(torch.sum(q, dim=2).shape)
torch.sum(q, dim=2)
# 2번째 인덱스에 있는 차원이 더해져 없어진다.

torch.Size([2, 3, 5])


tensor([[[ 30,  34,  38,  42,  46],
         [110, 114, 118, 122, 126],
         [190, 194, 198, 202, 206]],

        [[270, 274, 278, 282, 286],
         [350, 354, 358, 362, 366],
         [430, 434, 438, 442, 446]]])

In [ ]:
print(torch.sum(q, dim=3).shape)
torch.sum(q, dim=3)
# 3번째 인덱스에 있는 차원이 더해져 없어진다.

torch.Size([2, 3, 4])


tensor([[[ 10,  35,  60,  85],
         [110, 135, 160, 185],
         [210, 235, 260, 285]],

        [[310, 335, 360, 385],
         [410, 435, 460, 485],
         [510, 535, 560, 585]]])

# keepdim(bool)
 - default = False


keepdim => whether the output tensor has dim retained or not.  
합계산을 하고 나서 해당 dimension을 그대로 유지할건지 옵션임  



In [ ]:
a=  torch.arange(4*4).view(4,4)
print(a)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]])


In [ ]:
print(torch.sum(a,dim=1,keepdim=True).shape)
torch.sum(a,dim=1,keepdim=True)

torch.Size([4, 1])


tensor([[ 6],
        [22],
        [38],
        [54]])

In [ ]:
print(torch.sum(a,dim=1,keepdim=False).shape)
torch.sum(a,dim=1,keepdim=False)

torch.Size([4])


tensor([ 6, 22, 38, 54])

In [ ]:
x = torch.arange(2*3*4).view(2,3,4)
print(x.shape)
print(x)

torch.Size([2, 3, 4])
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])


In [ ]:
print(torch.sum(x,dim=1,keepdim=True).shape)
torch.sum(x,dim=1,keepdim=True)

torch.Size([2, 1, 4])


tensor([[[12, 15, 18, 21]],

        [[48, 51, 54, 57]]])

In [ ]:
print(torch.sum(x,dim=1,keepdim=False).shape)
torch.sum(x,dim=1,keepdim=False)

torch.Size([2, 4])


tensor([[12, 15, 18, 21],
        [48, 51, 54, 57]])

# backwor() 이해하기

In [15]:
import torch

y = torch.ones(1,3, requires_grad=True)
y = y * 2
y = y * y
y

tensor([[4., 4., 4.]], grad_fn=<MulBackward0>)

In [16]:
v = torch.tensor([[3,5,9]], dtype=torch.float)
y.backward(v)

print(y.grad)

None


<ipython-input-16-40655b1e4d7e>:4: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  print(y.grad)


In [17]:
a = torch.ones(2,2)
print(a)

tensor([[1., 1.],
        [1., 1.]])


In [18]:
a = torch.ones(2,2, requires_grad=True)
print(a)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [19]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
None
None


In [20]:
b = a + 2
print(b)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [21]:
c = b ** 2
print(c)

tensor([[9., 9.],
        [9., 9.]], grad_fn=<PowBackward0>)


In [22]:
out = c.sum()
print(out)

tensor(36., grad_fn=<SumBackward0>)


In [24]:
print(out)
out.backward()

tensor(36., grad_fn=<SumBackward0>)


In [25]:
print(a.data)
print(a.grad)
print(a.grad_fn)

tensor([[1., 1.],
        [1., 1.]])
tensor([[6., 6.],
        [6., 6.]])
None


In [34]:
a = torch.ones(2,2, requires_grad=True)
b = a + 2
c = b ** 2
out = c.sum()
out.backward()
print(a.grad)

tensor([[6., 6.],
        [6., 6.]])


In [31]:
print(out.grad)
print(c.grad)
print(b.grad)
print(a.grad)

None
None
None
tensor([[6., 6.],
        [6., 6.]])


<ipython-input-31-b2f3241f9feb>:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at aten/src/ATen/core/TensorBody.h:486.)
  print(out.grad)
<ipython-input-31-b2f3241f9feb>:2: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more i